"""remove external_id and source from ingredients, changed name length constraint

Revision ID: 11c2af436e19
Revises: 2680d0438c12
Create Date: 2025-08-28 18:28:39.548012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c2af436e19'
down_revision: Union[str, Sequence[str], None] = '2680d0438c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)

    with op.batch_alter_table('history_meals', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('UQ_ingredient_source_extid'), type_='unique')
        batch_op.drop_column('source')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=10), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('UQ_ingredient_source_extid'), ['source', 'external_id'])
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('history_meals', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
