"""fixed the stupid constraint should be positive

Revision ID: 14dbb10a2efd
Revises: 6cd9c96a3218
Create Date: 2025-08-30 17:05:36.890064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dbb10a2efd'
down_revision: Union[str, Sequence[str], None] = '6cd9c96a3218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
