"""fixed the stupid constraint that grams can be zero

Revision ID: 6cd9c96a3218
Revises: b0da3dd2bd11
Create Date: 2025-08-30 17:03:18.636051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd9c96a3218'
down_revision: Union[str, Sequence[str], None] = 'b0da3dd2bd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
