"""Change external_id to String

Revision ID: d3f579403e22
Revises: 9e56fd27d9c4
Create Date: 2025-08-04 20:56:35.239777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f579403e22'
down_revision: Union[str, Sequence[str], None] = '9e56fd27d9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('external_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('external_id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
